// <auto-generated />
using FoodOrderApi.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodOrderApi.Migrations
{
    [DbContext(typeof(FoodApiDbContext))]
    [Migration("20230524130053_Seeders")]
    partial class Seeders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("FoodOrderApi.Model.Domain.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductPrice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductID = 1,
                            ProductName = "Thai Broccoli Salad",
                            ProductPrice = "255",
                            RestaurantID = 1
                        },
                        new
                        {
                            Id = 2,
                            ProductID = 2,
                            ProductName = "Chettinad Cutlet",
                            ProductPrice = "275",
                            RestaurantID = 1
                        },
                        new
                        {
                            Id = 3,
                            ProductID = 3,
                            ProductName = "Curd Rice Aracini",
                            ProductPrice = "265",
                            RestaurantID = 1
                        },
                        new
                        {
                            Id = 4,
                            ProductID = 1,
                            ProductName = "Idly(2)",
                            ProductPrice = "33",
                            RestaurantID = 2
                        },
                        new
                        {
                            Id = 5,
                            ProductID = 2,
                            ProductName = "Pongal",
                            ProductPrice = "48",
                            RestaurantID = 2
                        },
                        new
                        {
                            Id = 6,
                            ProductID = 3,
                            ProductName = "Roast",
                            ProductPrice = "75",
                            RestaurantID = 2
                        },
                        new
                        {
                            Id = 7,
                            ProductID = 1,
                            ProductName = "Chocolate Sizzler",
                            ProductPrice = "299",
                            RestaurantID = 3
                        },
                        new
                        {
                            Id = 8,
                            ProductID = 2,
                            ProductName = "Choco Brownie Bomb",
                            ProductPrice = "249",
                            RestaurantID = 3
                        },
                        new
                        {
                            Id = 9,
                            ProductID = 3,
                            ProductName = "Chocolate Cookies",
                            ProductPrice = "199",
                            RestaurantID = 3
                        },
                        new
                        {
                            Id = 10,
                            ProductID = 1,
                            ProductName = "Vegetable Club Sandwich",
                            ProductPrice = "150",
                            RestaurantID = 4
                        },
                        new
                        {
                            Id = 11,
                            ProductID = 2,
                            ProductName = "Veg Combo Meal",
                            ProductPrice = "439",
                            RestaurantID = 4
                        },
                        new
                        {
                            Id = 12,
                            ProductID = 3,
                            ProductName = "Orbis Signature Rice",
                            ProductPrice = "250",
                            RestaurantID = 4
                        });
                });

            modelBuilder.Entity("FoodOrderApi.Model.Domain.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProductID (Numbers)");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FoodOrderApi.Model.Domain.Restaurant", b =>
                {
                    b.Property<int>("RestaurantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RestaurantLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RestaurantPhoneNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RestaurantType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RestaurantID");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            RestaurantID = 1,
                            RestaurantLocation = "RS Puram",
                            RestaurantName = "Kove",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Fine Dining"
                        },
                        new
                        {
                            RestaurantID = 2,
                            RestaurantLocation = "RS Puram",
                            RestaurantName = "Annapoorna",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Casual Dining"
                        },
                        new
                        {
                            RestaurantID = 3,
                            RestaurantLocation = "Race Course Road",
                            RestaurantName = "Chocolate Room",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Desserts and Beerages"
                        },
                        new
                        {
                            RestaurantID = 4,
                            RestaurantLocation = "Avinashi Road",
                            RestaurantName = "Orbis",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Multi Cuisine"
                        });
                });

            modelBuilder.Entity("FoodOrderApi.Model.Domain.RestaurantWithMenu", b =>
                {
                    b.Property<int>("RestaurantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Menus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RestaurantLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RestaurantPhoneNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RestaurantType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RestaurantID");

                    b.ToTable("RestaurantWithMenus");

                    b.HasData(
                        new
                        {
                            RestaurantID = 1,
                            Menus = "Thai Broccoli Salad,Curd Rice Aracini,Chettinad Cutlet\r\n",
                            RestaurantLocation = "RS Puram",
                            RestaurantName = "Kove",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Fine Dining"
                        },
                        new
                        {
                            RestaurantID = 2,
                            Menus = "Idly(2),Pongal,Roast\r\n",
                            RestaurantLocation = "RS Puram",
                            RestaurantName = "Annapoorna",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Casual Dining"
                        },
                        new
                        {
                            RestaurantID = 3,
                            Menus = "Chocolate Sizzler,Choco Brownie Bomb,Chocolate Cookies\r\n",
                            RestaurantLocation = "Race Course Road",
                            RestaurantName = "Chocolate Room",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Desserts and Beerages"
                        },
                        new
                        {
                            RestaurantID = 4,
                            Menus = "Vegetable Club Sandwich,Veg Combo Meal,Orbis Signature Rice\r\n",
                            RestaurantLocation = "Avinashi Road",
                            RestaurantName = "Orbis",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Multi Cuisine"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
