// <auto-generated />
using System;
using FoodOrderApi.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodOrderApi.Migrations
{
    [DbContext(typeof(FoodApiDbContext))]
    partial class FoodApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("FoodOrderApi.Model.Domain.Menu", b =>
                {
                    b.Property<Guid>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Item ID");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Item Name");

                    b.Property<double>("ProductOffer")
                        .HasColumnType("REAL")
                        .HasColumnName("Item Discount (%)");

                    b.Property<double>("ProductPrice")
                        .HasPrecision(2, 3)
                        .HasColumnType("REAL")
                        .HasColumnName("Item Price (₹)");

                    b.Property<Guid>("RestaurantID")
                        .HasColumnType("TEXT")
                        .HasColumnName("Restaurant ID");

                    b.HasKey("ProductID");

                    b.HasIndex("RestaurantID");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            ProductID = new Guid("e0194510-6ad1-4ac2-bf31-e572caa09ba1"),
                            ProductName = "Thai Broccoli Salad",
                            ProductOffer = 10.0,
                            ProductPrice = 205.0,
                            RestaurantID = new Guid("baad586a-accf-4433-98f0-2f861e683354")
                        },
                        new
                        {
                            ProductID = new Guid("983fc832-5371-4bdc-af27-bd14f5998f44"),
                            ProductName = "Curd Rice Aracini",
                            ProductOffer = 20.0,
                            ProductPrice = 200.0,
                            RestaurantID = new Guid("baad586a-accf-4433-98f0-2f861e683354")
                        },
                        new
                        {
                            ProductID = new Guid("ae527a12-be03-4ac1-8206-7345a1a90bf6"),
                            ProductName = "Chettinad Cutlet",
                            ProductOffer = 30.0,
                            ProductPrice = 255.0,
                            RestaurantID = new Guid("baad586a-accf-4433-98f0-2f861e683354")
                        },
                        new
                        {
                            ProductID = new Guid("26986da6-4610-472e-b14a-30a713bdd30e"),
                            ProductName = "Thai Broccoli Salad",
                            ProductOffer = 10.0,
                            ProductPrice = 205.0,
                            RestaurantID = new Guid("f40029f8-9c8f-4abf-8db5-ffa00a13d1cd")
                        },
                        new
                        {
                            ProductID = new Guid("f2612c12-b189-4d23-9532-e7c07a1eebe3"),
                            ProductName = "Curd Rice Aracini",
                            ProductOffer = 20.0,
                            ProductPrice = 275.0,
                            RestaurantID = new Guid("f40029f8-9c8f-4abf-8db5-ffa00a13d1cd")
                        },
                        new
                        {
                            ProductID = new Guid("d636db98-a948-45ab-956b-9078a9252a42"),
                            ProductName = "Chettinad Cutlet",
                            ProductOffer = 30.0,
                            ProductPrice = 255.0,
                            RestaurantID = new Guid("f40029f8-9c8f-4abf-8db5-ffa00a13d1cd")
                        },
                        new
                        {
                            ProductID = new Guid("b6b56f12-0ac4-401c-82c6-9a5103870ed8"),
                            ProductName = "Thai Broccoli Salad",
                            ProductOffer = 10.0,
                            ProductPrice = 200.0,
                            RestaurantID = new Guid("d487c6ec-2a8b-44a1-ba0e-f4ff24a9e7ce")
                        },
                        new
                        {
                            ProductID = new Guid("f613a27f-93c2-4028-9deb-ddc4b8b45e3a"),
                            ProductName = "Curd Rice Aracini",
                            ProductOffer = 20.0,
                            ProductPrice = 265.0,
                            RestaurantID = new Guid("d487c6ec-2a8b-44a1-ba0e-f4ff24a9e7ce")
                        },
                        new
                        {
                            ProductID = new Guid("289f9767-e25f-407d-ae50-72c3debe8ced"),
                            ProductName = "Chettinad Cutlet",
                            ProductOffer = 30.0,
                            ProductPrice = 255.0,
                            RestaurantID = new Guid("d487c6ec-2a8b-44a1-ba0e-f4ff24a9e7ce")
                        },
                        new
                        {
                            ProductID = new Guid("0c976706-286a-4f66-a65b-12461d8847fb"),
                            ProductName = "Thai Broccoli Salad",
                            ProductOffer = 10.0,
                            ProductPrice = 200.0,
                            RestaurantID = new Guid("a082a822-c7f0-4ea0-837d-957a5b154908")
                        },
                        new
                        {
                            ProductID = new Guid("999c9f43-5153-4e08-b471-1015bf08498e"),
                            ProductName = "Curd Rice Aracini",
                            ProductOffer = 20.0,
                            ProductPrice = 205.0,
                            RestaurantID = new Guid("a082a822-c7f0-4ea0-837d-957a5b154908")
                        },
                        new
                        {
                            ProductID = new Guid("768b93dd-e9d4-4a64-941c-cf4a902b75a6"),
                            ProductName = "Chettinad Cutlet",
                            ProductOffer = 30.0,
                            ProductPrice = 255.0,
                            RestaurantID = new Guid("a082a822-c7f0-4ea0-837d-957a5b154908")
                        },
                        new
                        {
                            ProductID = new Guid("2318c8a7-f867-415d-8427-df4bbe527796"),
                            ProductName = "Thai Broccoli Salad",
                            ProductOffer = 10.0,
                            ProductPrice = 200.0,
                            RestaurantID = new Guid("ee05c50f-d96e-4fd8-b84e-708c772dc026")
                        },
                        new
                        {
                            ProductID = new Guid("0bd3debf-0ec8-4cb4-9497-e76da79eb9c8"),
                            ProductName = "Curd Rice Aracini",
                            ProductOffer = 20.0,
                            ProductPrice = 205.0,
                            RestaurantID = new Guid("ee05c50f-d96e-4fd8-b84e-708c772dc026")
                        },
                        new
                        {
                            ProductID = new Guid("f1b97db8-9b54-4616-8d49-b36e4cd08f5f"),
                            ProductName = "Chettinad Cutlet",
                            ProductOffer = 30.0,
                            ProductPrice = 255.0,
                            RestaurantID = new Guid("ee05c50f-d96e-4fd8-b84e-708c772dc026")
                        },
                        new
                        {
                            ProductID = new Guid("ea6460df-d676-426c-8699-ae19230d743e"),
                            ProductName = "Thai Broccoli Salad",
                            ProductOffer = 10.0,
                            ProductPrice = 200.0,
                            RestaurantID = new Guid("6069ced7-f6cf-4d8d-999e-78566375ad55")
                        },
                        new
                        {
                            ProductID = new Guid("6c9ba650-6204-4ba0-9602-4413932e36b1"),
                            ProductName = "Curd Rice Aracini",
                            ProductOffer = 20.0,
                            ProductPrice = 205.0,
                            RestaurantID = new Guid("6069ced7-f6cf-4d8d-999e-78566375ad55")
                        },
                        new
                        {
                            ProductID = new Guid("019ec633-f286-4955-b473-d510daf80960"),
                            ProductName = "Chettinad Cutlet",
                            ProductOffer = 30.0,
                            ProductPrice = 255.0,
                            RestaurantID = new Guid("6069ced7-f6cf-4d8d-999e-78566375ad55")
                        },
                        new
                        {
                            ProductID = new Guid("cfa81f1b-9db5-43a4-962d-506e68615495"),
                            ProductName = "Thai Broccoli Salad",
                            ProductOffer = 10.0,
                            ProductPrice = 200.0,
                            RestaurantID = new Guid("0c2b4710-050e-4794-8031-e5fc19ef13b4")
                        },
                        new
                        {
                            ProductID = new Guid("8de20733-568b-430d-b642-a3a5254b6418"),
                            ProductName = "Curd Rice Aracini",
                            ProductOffer = 20.0,
                            ProductPrice = 205.0,
                            RestaurantID = new Guid("0c2b4710-050e-4794-8031-e5fc19ef13b4")
                        },
                        new
                        {
                            ProductID = new Guid("6fa050ad-d0c1-41f0-a131-610c3e78e03d"),
                            ProductName = "Chettinad Cutlet",
                            ProductOffer = 30.0,
                            ProductPrice = 255.0,
                            RestaurantID = new Guid("0c2b4710-050e-4794-8031-e5fc19ef13b4")
                        },
                        new
                        {
                            ProductID = new Guid("be5a857b-1336-4d13-a1d8-b0c9683689ca"),
                            ProductName = "Idly(2)",
                            ProductOffer = 10.0,
                            ProductPrice = 33.0,
                            RestaurantID = new Guid("7e83a461-5a28-4b11-83a5-31458449b7ac")
                        },
                        new
                        {
                            ProductID = new Guid("780717ad-8473-4c23-b9b0-a256fd80f13f"),
                            ProductName = "Pongal",
                            ProductOffer = 20.0,
                            ProductPrice = 48.0,
                            RestaurantID = new Guid("7e83a461-5a28-4b11-83a5-31458449b7ac")
                        },
                        new
                        {
                            ProductID = new Guid("e1764da4-941d-463a-8531-43b701306780"),
                            ProductName = "Roast",
                            ProductOffer = 30.0,
                            ProductPrice = 75.0,
                            RestaurantID = new Guid("7e83a461-5a28-4b11-83a5-31458449b7ac")
                        },
                        new
                        {
                            ProductID = new Guid("1ff36c1a-3e10-4651-88e4-7fc4736bf4d8"),
                            ProductName = "Chocolate Sizzler",
                            ProductOffer = 10.0,
                            ProductPrice = 299.0,
                            RestaurantID = new Guid("7a03ca50-719f-48e7-ae0e-e4e299f3112b")
                        },
                        new
                        {
                            ProductID = new Guid("316dc710-146c-430b-9b0f-e9aa51b1e8e9"),
                            ProductName = "Choco Brownie Bomb",
                            ProductOffer = 20.0,
                            ProductPrice = 249.0,
                            RestaurantID = new Guid("7a03ca50-719f-48e7-ae0e-e4e299f3112b")
                        },
                        new
                        {
                            ProductID = new Guid("3a011230-db41-4407-9218-347f51391818"),
                            ProductName = "Chocolate Cookies",
                            ProductOffer = 30.0,
                            ProductPrice = 199.0,
                            RestaurantID = new Guid("7a03ca50-719f-48e7-ae0e-e4e299f3112b")
                        },
                        new
                        {
                            ProductID = new Guid("c8e03d8c-3438-4583-b12e-1ba54c3670d6"),
                            ProductName = "Vegetable Club Sandwich",
                            ProductOffer = 10.0,
                            ProductPrice = 150.0,
                            RestaurantID = new Guid("2818b184-94be-4a91-a3b8-a510b00bd6f5")
                        },
                        new
                        {
                            ProductID = new Guid("a91be131-8704-45ae-9ba7-60e70c58abb4"),
                            ProductName = "Veg Combo Meal",
                            ProductOffer = 20.0,
                            ProductPrice = 439.0,
                            RestaurantID = new Guid("2818b184-94be-4a91-a3b8-a510b00bd6f5")
                        },
                        new
                        {
                            ProductID = new Guid("5849b06f-9731-4e31-a908-6e7e9dafdd5a"),
                            ProductName = "Orbis Signature Rice",
                            ProductOffer = 30.0,
                            ProductPrice = 250.0,
                            RestaurantID = new Guid("2818b184-94be-4a91-a3b8-a510b00bd6f5")
                        });
                });

            modelBuilder.Entity("FoodOrderApi.Model.Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Customer Name");

                    b.Property<string>("IsDelivered")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Status");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RestaurantID")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductID");

                    b.HasIndex("RestaurantID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FoodOrderApi.Model.Domain.Restaurant", b =>
                {
                    b.Property<Guid>("RestaurantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("RestaurantLocation")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Address");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<int>("RestaurantPhoneNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Phone Number");

                    b.Property<string>("RestaurantType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Type");

                    b.HasKey("RestaurantID");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            RestaurantID = new Guid("baad586a-accf-4433-98f0-2f861e683354"),
                            RestaurantLocation = "Ramanathpuram",
                            RestaurantName = "Kove",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Fine Dining"
                        },
                        new
                        {
                            RestaurantID = new Guid("f40029f8-9c8f-4abf-8db5-ffa00a13d1cd"),
                            RestaurantLocation = "Peelamedu",
                            RestaurantName = "Anadha Bhavan",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Fine Dining"
                        },
                        new
                        {
                            RestaurantID = new Guid("d487c6ec-2a8b-44a1-ba0e-f4ff24a9e7ce"),
                            RestaurantLocation = "Perambur",
                            RestaurantName = "Adyar Anadha Bhavan",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Fine Dining"
                        },
                        new
                        {
                            RestaurantID = new Guid("a082a822-c7f0-4ea0-837d-957a5b154908"),
                            RestaurantLocation = "Kalpakam",
                            RestaurantName = "Arya Bhavan",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Fine Dining"
                        },
                        new
                        {
                            RestaurantID = new Guid("6069ced7-f6cf-4d8d-999e-78566375ad55"),
                            RestaurantLocation = "Mars",
                            RestaurantName = "Mario Hotel",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Fine Dining"
                        },
                        new
                        {
                            RestaurantID = new Guid("0c2b4710-050e-4794-8031-e5fc19ef13b4"),
                            RestaurantLocation = "Jupiter",
                            RestaurantName = "KB Bhavan",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Fine Dining"
                        },
                        new
                        {
                            RestaurantID = new Guid("ee05c50f-d96e-4fd8-b84e-708c772dc026"),
                            RestaurantLocation = "Pluto",
                            RestaurantName = "SMS Hotel",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Fine Dining"
                        },
                        new
                        {
                            RestaurantID = new Guid("7e83a461-5a28-4b11-83a5-31458449b7ac"),
                            RestaurantLocation = "RS Puram",
                            RestaurantName = "Annapoorna",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Casual Dining"
                        },
                        new
                        {
                            RestaurantID = new Guid("7a03ca50-719f-48e7-ae0e-e4e299f3112b"),
                            RestaurantLocation = "Race Course Road",
                            RestaurantName = "Chocolate Room",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Desserts and Beerages"
                        },
                        new
                        {
                            RestaurantID = new Guid("2818b184-94be-4a91-a3b8-a510b00bd6f5"),
                            RestaurantLocation = "Avinashi Road",
                            RestaurantName = "Orbis",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Multi Cuisine"
                        });
                });

            modelBuilder.Entity("FoodOrderApi.Model.Domain.RestaurantWithMenu", b =>
                {
                    b.Property<Guid>("RestaurantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Menus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RestaurantLocation")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Address");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<int>("RestaurantPhoneNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Phone Number");

                    b.Property<string>("RestaurantType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Type");

                    b.HasKey("RestaurantID");

                    b.ToTable("RestaurantWithMenus");

                    b.HasData(
                        new
                        {
                            RestaurantID = new Guid("baad586a-accf-4433-98f0-2f861e683354"),
                            Menus = "Thai Broccoli Salad,Curd Rice Aracini,Chettinad Cutlet\r\n",
                            RestaurantLocation = "Ramanathpuram",
                            RestaurantName = "Kove",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Fine Dining"
                        },
                        new
                        {
                            RestaurantID = new Guid("f40029f8-9c8f-4abf-8db5-ffa00a13d1cd"),
                            Menus = "Thai Broccoli Salad,Curd Rice Aracini,Chettinad Cutlet\r\n",
                            RestaurantLocation = "Peelamedu",
                            RestaurantName = "Anadha Bhavan",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Fine Dining"
                        },
                        new
                        {
                            RestaurantID = new Guid("d487c6ec-2a8b-44a1-ba0e-f4ff24a9e7ce"),
                            Menus = "Thai Broccoli Salad,Curd Rice Aracini,Chettinad Cutlet\r\n",
                            RestaurantLocation = "Perambur",
                            RestaurantName = "Adyar Anadha Bhavan",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Fine Dining"
                        },
                        new
                        {
                            RestaurantID = new Guid("a082a822-c7f0-4ea0-837d-957a5b154908"),
                            Menus = "Thai Broccoli Salad,Curd Rice Aracini,Chettinad Cutlet\r\n",
                            RestaurantLocation = "Kalpakam",
                            RestaurantName = "Arya Bhavan",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Fine Dining"
                        },
                        new
                        {
                            RestaurantID = new Guid("6069ced7-f6cf-4d8d-999e-78566375ad55"),
                            Menus = "Thai Broccoli Salad,Curd Rice Aracini,Chettinad Cutlet\r\n",
                            RestaurantLocation = "Mars",
                            RestaurantName = "Mario Hotel",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Fine Dining"
                        },
                        new
                        {
                            RestaurantID = new Guid("0c2b4710-050e-4794-8031-e5fc19ef13b4"),
                            Menus = "Thai Broccoli Salad,Curd Rice Aracini,Chettinad Cutlet\r\n",
                            RestaurantLocation = "Jupiter",
                            RestaurantName = "KB Bhavan",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Fine Dining"
                        },
                        new
                        {
                            RestaurantID = new Guid("ee05c50f-d96e-4fd8-b84e-708c772dc026"),
                            Menus = "Thai Broccoli Salad,Curd Rice Aracini,Chettinad Cutlet\r\n",
                            RestaurantLocation = "Pluto",
                            RestaurantName = "SMS Hotel",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Fine Dining"
                        },
                        new
                        {
                            RestaurantID = new Guid("7e83a461-5a28-4b11-83a5-31458449b7ac"),
                            Menus = "Idly(2),Pongal,Roast\r\n",
                            RestaurantLocation = "RS Puram",
                            RestaurantName = "Annapoorna",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Casual Dining"
                        },
                        new
                        {
                            RestaurantID = new Guid("7a03ca50-719f-48e7-ae0e-e4e299f3112b"),
                            Menus = "Chocolate Sizzler,Choco Brownie Bomb,Chocolate Cookies\r\n",
                            RestaurantLocation = "Race Course Road",
                            RestaurantName = "Chocolate Room",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Desserts and Beerages"
                        },
                        new
                        {
                            RestaurantID = new Guid("2818b184-94be-4a91-a3b8-a510b00bd6f5"),
                            Menus = "Vegetable Club Sandwich,Veg Combo Meal,Orbis Signature Rice\r\n",
                            RestaurantLocation = "Avinashi Road",
                            RestaurantName = "Orbis",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Multi Cuisine"
                        });
                });

            modelBuilder.Entity("FoodOrderApi.Model.Domain.Menu", b =>
                {
                    b.HasOne("FoodOrderApi.Model.Domain.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("FoodOrderApi.Model.Domain.Order", b =>
                {
                    b.HasOne("FoodOrderApi.Model.Domain.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodOrderApi.Model.Domain.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Restaurant");
                });
#pragma warning restore 612, 618
        }
    }
}
