// <auto-generated />
using System;
using FoodOrderApi.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodOrderApi.Migrations
{
    [DbContext(typeof(FoodApiDbContext))]
    partial class FoodApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("FoodOrderApi.Model.Domain.Menu", b =>
                {
                    b.Property<Guid>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductPrice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RestaurantID")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductID");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            ProductID = new Guid("e0194510-6ad1-4ac2-bf31-e572caa09ba1"),
                            ProductName = "Thai Broccoli Salad",
                            ProductPrice = "255",
                            RestaurantID = new Guid("baad586a-accf-4433-98f0-2f861e683354")
                        },
                        new
                        {
                            ProductID = new Guid("f2612c12-b189-4d23-9532-e7c07a1eebe3"),
                            ProductName = "Chettinad Cutlet",
                            ProductPrice = "275",
                            RestaurantID = new Guid("baad586a-accf-4433-98f0-2f861e683354")
                        },
                        new
                        {
                            ProductID = new Guid("f613a27f-93c2-4028-9deb-ddc4b8b45e3a"),
                            ProductName = "Curd Rice Aracini",
                            ProductPrice = "265",
                            RestaurantID = new Guid("baad586a-accf-4433-98f0-2f861e683354")
                        },
                        new
                        {
                            ProductID = new Guid("be5a857b-1336-4d13-a1d8-b0c9683689ca"),
                            ProductName = "Idly(2)",
                            ProductPrice = "33",
                            RestaurantID = new Guid("7e83a461-5a28-4b11-83a5-31458449b7ac")
                        },
                        new
                        {
                            ProductID = new Guid("780717ad-8473-4c23-b9b0-a256fd80f13f"),
                            ProductName = "Pongal",
                            ProductPrice = "48",
                            RestaurantID = new Guid("7e83a461-5a28-4b11-83a5-31458449b7ac")
                        },
                        new
                        {
                            ProductID = new Guid("e1764da4-941d-463a-8531-43b701306780"),
                            ProductName = "Roast",
                            ProductPrice = "75",
                            RestaurantID = new Guid("7e83a461-5a28-4b11-83a5-31458449b7ac")
                        },
                        new
                        {
                            ProductID = new Guid("1ff36c1a-3e10-4651-88e4-7fc4736bf4d8"),
                            ProductName = "Chocolate Sizzler",
                            ProductPrice = "299",
                            RestaurantID = new Guid("7a03ca50-719f-48e7-ae0e-e4e299f3112b")
                        },
                        new
                        {
                            ProductID = new Guid("316dc710-146c-430b-9b0f-e9aa51b1e8e9"),
                            ProductName = "Choco Brownie Bomb",
                            ProductPrice = "249",
                            RestaurantID = new Guid("7a03ca50-719f-48e7-ae0e-e4e299f3112b")
                        },
                        new
                        {
                            ProductID = new Guid("3a011230-db41-4407-9218-347f51391818"),
                            ProductName = "Chocolate Cookies",
                            ProductPrice = "199",
                            RestaurantID = new Guid("7a03ca50-719f-48e7-ae0e-e4e299f3112b")
                        },
                        new
                        {
                            ProductID = new Guid("c8e03d8c-3438-4583-b12e-1ba54c3670d6"),
                            ProductName = "Vegetable Club Sandwich",
                            ProductPrice = "150",
                            RestaurantID = new Guid("2818b184-94be-4a91-a3b8-a510b00bd6f5")
                        },
                        new
                        {
                            ProductID = new Guid("a91be131-8704-45ae-9ba7-60e70c58abb4"),
                            ProductName = "Veg Combo Meal",
                            ProductPrice = "439",
                            RestaurantID = new Guid("2818b184-94be-4a91-a3b8-a510b00bd6f5")
                        },
                        new
                        {
                            ProductID = new Guid("5849b06f-9731-4e31-a908-6e7e9dafdd5a"),
                            ProductName = "Orbis Signature Rice",
                            ProductPrice = "250",
                            RestaurantID = new Guid("2818b184-94be-4a91-a3b8-a510b00bd6f5")
                        });
                });

            modelBuilder.Entity("FoodOrderApi.Model.Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("TEXT")
                        .HasColumnName("ProductID (Numbers)");

                    b.Property<Guid>("RestaurantID")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductID");

                    b.HasIndex("RestaurantID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FoodOrderApi.Model.Domain.Restaurant", b =>
                {
                    b.Property<Guid>("RestaurantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("RestaurantLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RestaurantPhoneNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RestaurantType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RestaurantID");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            RestaurantID = new Guid("baad586a-accf-4433-98f0-2f861e683354"),
                            RestaurantLocation = "RS Puram",
                            RestaurantName = "Kove",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Fine Dining"
                        },
                        new
                        {
                            RestaurantID = new Guid("7e83a461-5a28-4b11-83a5-31458449b7ac"),
                            RestaurantLocation = "RS Puram",
                            RestaurantName = "Annapoorna",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Casual Dining"
                        },
                        new
                        {
                            RestaurantID = new Guid("7a03ca50-719f-48e7-ae0e-e4e299f3112b"),
                            RestaurantLocation = "Race Course Road",
                            RestaurantName = "Chocolate Room",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Desserts and Beerages"
                        },
                        new
                        {
                            RestaurantID = new Guid("2818b184-94be-4a91-a3b8-a510b00bd6f5"),
                            RestaurantLocation = "Avinashi Road",
                            RestaurantName = "Orbis",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Multi Cuisine"
                        });
                });

            modelBuilder.Entity("FoodOrderApi.Model.Domain.RestaurantWithMenu", b =>
                {
                    b.Property<Guid>("RestaurantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Menus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RestaurantLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RestaurantPhoneNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RestaurantType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RestaurantID");

                    b.ToTable("RestaurantWithMenus");

                    b.HasData(
                        new
                        {
                            RestaurantID = new Guid("baad586a-accf-4433-98f0-2f861e683354"),
                            Menus = "Thai Broccoli Salad,Curd Rice Aracini,Chettinad Cutlet\r\n",
                            RestaurantLocation = "RS Puram",
                            RestaurantName = "Kove",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Fine Dining"
                        },
                        new
                        {
                            RestaurantID = new Guid("7e83a461-5a28-4b11-83a5-31458449b7ac"),
                            Menus = "Idly(2),Pongal,Roast\r\n",
                            RestaurantLocation = "RS Puram",
                            RestaurantName = "Annapoorna",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Casual Dining"
                        },
                        new
                        {
                            RestaurantID = new Guid("7a03ca50-719f-48e7-ae0e-e4e299f3112b"),
                            Menus = "Chocolate Sizzler,Choco Brownie Bomb,Chocolate Cookies\r\n",
                            RestaurantLocation = "Race Course Road",
                            RestaurantName = "Chocolate Room",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Desserts and Beerages"
                        },
                        new
                        {
                            RestaurantID = new Guid("2818b184-94be-4a91-a3b8-a510b00bd6f5"),
                            Menus = "Vegetable Club Sandwich,Veg Combo Meal,Orbis Signature Rice\r\n",
                            RestaurantLocation = "Avinashi Road",
                            RestaurantName = "Orbis",
                            RestaurantPhoneNumber = 1234567890,
                            RestaurantType = "Multi Cuisine"
                        });
                });

            modelBuilder.Entity("FoodOrderApi.Model.Domain.Order", b =>
                {
                    b.HasOne("FoodOrderApi.Model.Domain.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodOrderApi.Model.Domain.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Restaurant");
                });
#pragma warning restore 612, 618
        }
    }
}
